version: '4.7.1'

services:
  node_backed:
    container_name: api_posts
    image : api_posts:0.0.4
    build:
      context: .
    ports: 
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
      - PGDATABASE=posts
      - PGUSER=postgres
      - PGPASSWORD=admin
      - PGHOST=node_db
    depends_on: 
      - node_db
  node_db:
    container_name : node_db
    image: "postgres:12"
    ports:  
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=posts
    volumes:
      - nps_data:/var/lib/postgresql/data
volumes:
  nps_data: {}